/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as onboardingRouteRouteImport } from './routes/(onboarding)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as WorkspaceSlugRouteRouteImport } from './routes/$workspaceSlug/route'
import { Route as WorkspaceSlugSettingsRouteRouteImport } from './routes/$workspaceSlug/settings/route'
import { Route as WorkspaceSlugwithSidebarRouteRouteImport } from './routes/$workspaceSlug/(with-sidebar)/route'
import { Route as onboardingCreateWorkspaceIndexRouteImport } from './routes/(onboarding)/create-workspace/index'
import { Route as authSignUpIndexRouteImport } from './routes/(auth)/sign-up/index'
import { Route as authSignInIndexRouteImport } from './routes/(auth)/sign-in/index'
import { Route as WorkspaceSlugSettingsIndexRouteImport } from './routes/$workspaceSlug/settings/index'
import { Route as WorkspaceSlugwithSidebarIndexRouteImport } from './routes/$workspaceSlug/(with-sidebar)/index'
import { Route as WorkspaceSlugSettingsProfileIndexRouteImport } from './routes/$workspaceSlug/settings/profile/index'

const onboardingRouteRoute = onboardingRouteRouteImport.update({
  id: '/(onboarding)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugRouteRoute = WorkspaceSlugRouteRouteImport.update({
  id: '/$workspaceSlug',
  path: '/$workspaceSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugSettingsRouteRoute =
  WorkspaceSlugSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WorkspaceSlugRouteRoute,
  } as any)
const WorkspaceSlugwithSidebarRouteRoute =
  WorkspaceSlugwithSidebarRouteRouteImport.update({
    id: '/(with-sidebar)',
    getParentRoute: () => WorkspaceSlugRouteRoute,
  } as any)
const onboardingCreateWorkspaceIndexRoute =
  onboardingCreateWorkspaceIndexRouteImport.update({
    id: '/create-workspace/',
    path: '/create-workspace/',
    getParentRoute: () => onboardingRouteRoute,
  } as any)
const authSignUpIndexRoute = authSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInIndexRoute = authSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => authRouteRoute,
} as any)
const WorkspaceSlugSettingsIndexRoute =
  WorkspaceSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceSlugSettingsRouteRoute,
  } as any)
const WorkspaceSlugwithSidebarIndexRoute =
  WorkspaceSlugwithSidebarIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceSlugwithSidebarRouteRoute,
  } as any)
const WorkspaceSlugSettingsProfileIndexRoute =
  WorkspaceSlugSettingsProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => WorkspaceSlugSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$workspaceSlug': typeof WorkspaceSlugRouteRouteWithChildren
  '/': typeof onboardingRouteRouteWithChildren
  '/$workspaceSlug/': typeof WorkspaceSlugwithSidebarIndexRoute
  '/$workspaceSlug/settings': typeof WorkspaceSlugSettingsRouteRouteWithChildren
  '/$workspaceSlug/settings/': typeof WorkspaceSlugSettingsIndexRoute
  '/sign-in': typeof authSignInIndexRoute
  '/sign-up': typeof authSignUpIndexRoute
  '/create-workspace': typeof onboardingCreateWorkspaceIndexRoute
  '/$workspaceSlug/settings/profile': typeof WorkspaceSlugSettingsProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof onboardingRouteRouteWithChildren
  '/$workspaceSlug': typeof WorkspaceSlugwithSidebarIndexRoute
  '/$workspaceSlug/settings': typeof WorkspaceSlugSettingsIndexRoute
  '/sign-in': typeof authSignInIndexRoute
  '/sign-up': typeof authSignUpIndexRoute
  '/create-workspace': typeof onboardingCreateWorkspaceIndexRoute
  '/$workspaceSlug/settings/profile': typeof WorkspaceSlugSettingsProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$workspaceSlug': typeof WorkspaceSlugRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(onboarding)': typeof onboardingRouteRouteWithChildren
  '/$workspaceSlug/(with-sidebar)': typeof WorkspaceSlugwithSidebarRouteRouteWithChildren
  '/$workspaceSlug/settings': typeof WorkspaceSlugSettingsRouteRouteWithChildren
  '/$workspaceSlug/(with-sidebar)/': typeof WorkspaceSlugwithSidebarIndexRoute
  '/$workspaceSlug/settings/': typeof WorkspaceSlugSettingsIndexRoute
  '/(auth)/sign-in/': typeof authSignInIndexRoute
  '/(auth)/sign-up/': typeof authSignUpIndexRoute
  '/(onboarding)/create-workspace/': typeof onboardingCreateWorkspaceIndexRoute
  '/$workspaceSlug/settings/profile/': typeof WorkspaceSlugSettingsProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$workspaceSlug'
    | '/'
    | '/$workspaceSlug/'
    | '/$workspaceSlug/settings'
    | '/$workspaceSlug/settings/'
    | '/sign-in'
    | '/sign-up'
    | '/create-workspace'
    | '/$workspaceSlug/settings/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$workspaceSlug'
    | '/$workspaceSlug/settings'
    | '/sign-in'
    | '/sign-up'
    | '/create-workspace'
    | '/$workspaceSlug/settings/profile'
  id:
    | '__root__'
    | '/$workspaceSlug'
    | '/(auth)'
    | '/(onboarding)'
    | '/$workspaceSlug/(with-sidebar)'
    | '/$workspaceSlug/settings'
    | '/$workspaceSlug/(with-sidebar)/'
    | '/$workspaceSlug/settings/'
    | '/(auth)/sign-in/'
    | '/(auth)/sign-up/'
    | '/(onboarding)/create-workspace/'
    | '/$workspaceSlug/settings/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkspaceSlugRouteRoute: typeof WorkspaceSlugRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  onboardingRouteRoute: typeof onboardingRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(onboarding)': {
      id: '/(onboarding)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof onboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug': {
      id: '/$workspaceSlug'
      path: '/$workspaceSlug'
      fullPath: '/$workspaceSlug'
      preLoaderRoute: typeof WorkspaceSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/settings': {
      id: '/$workspaceSlug/settings'
      path: '/settings'
      fullPath: '/$workspaceSlug/settings'
      preLoaderRoute: typeof WorkspaceSlugSettingsRouteRouteImport
      parentRoute: typeof WorkspaceSlugRouteRoute
    }
    '/$workspaceSlug/(with-sidebar)': {
      id: '/$workspaceSlug/(with-sidebar)'
      path: '/'
      fullPath: '/$workspaceSlug/'
      preLoaderRoute: typeof WorkspaceSlugwithSidebarRouteRouteImport
      parentRoute: typeof WorkspaceSlugRouteRoute
    }
    '/(onboarding)/create-workspace/': {
      id: '/(onboarding)/create-workspace/'
      path: '/create-workspace'
      fullPath: '/create-workspace'
      preLoaderRoute: typeof onboardingCreateWorkspaceIndexRouteImport
      parentRoute: typeof onboardingRouteRoute
    }
    '/(auth)/sign-up/': {
      id: '/(auth)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in/': {
      id: '/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/$workspaceSlug/settings/': {
      id: '/$workspaceSlug/settings/'
      path: '/'
      fullPath: '/$workspaceSlug/settings/'
      preLoaderRoute: typeof WorkspaceSlugSettingsIndexRouteImport
      parentRoute: typeof WorkspaceSlugSettingsRouteRoute
    }
    '/$workspaceSlug/(with-sidebar)/': {
      id: '/$workspaceSlug/(with-sidebar)/'
      path: '/'
      fullPath: '/$workspaceSlug/'
      preLoaderRoute: typeof WorkspaceSlugwithSidebarIndexRouteImport
      parentRoute: typeof WorkspaceSlugwithSidebarRouteRoute
    }
    '/$workspaceSlug/settings/profile/': {
      id: '/$workspaceSlug/settings/profile/'
      path: '/profile'
      fullPath: '/$workspaceSlug/settings/profile'
      preLoaderRoute: typeof WorkspaceSlugSettingsProfileIndexRouteImport
      parentRoute: typeof WorkspaceSlugSettingsRouteRoute
    }
  }
}

interface WorkspaceSlugwithSidebarRouteRouteChildren {
  WorkspaceSlugwithSidebarIndexRoute: typeof WorkspaceSlugwithSidebarIndexRoute
}

const WorkspaceSlugwithSidebarRouteRouteChildren: WorkspaceSlugwithSidebarRouteRouteChildren =
  {
    WorkspaceSlugwithSidebarIndexRoute: WorkspaceSlugwithSidebarIndexRoute,
  }

const WorkspaceSlugwithSidebarRouteRouteWithChildren =
  WorkspaceSlugwithSidebarRouteRoute._addFileChildren(
    WorkspaceSlugwithSidebarRouteRouteChildren,
  )

interface WorkspaceSlugSettingsRouteRouteChildren {
  WorkspaceSlugSettingsIndexRoute: typeof WorkspaceSlugSettingsIndexRoute
  WorkspaceSlugSettingsProfileIndexRoute: typeof WorkspaceSlugSettingsProfileIndexRoute
}

const WorkspaceSlugSettingsRouteRouteChildren: WorkspaceSlugSettingsRouteRouteChildren =
  {
    WorkspaceSlugSettingsIndexRoute: WorkspaceSlugSettingsIndexRoute,
    WorkspaceSlugSettingsProfileIndexRoute:
      WorkspaceSlugSettingsProfileIndexRoute,
  }

const WorkspaceSlugSettingsRouteRouteWithChildren =
  WorkspaceSlugSettingsRouteRoute._addFileChildren(
    WorkspaceSlugSettingsRouteRouteChildren,
  )

interface WorkspaceSlugRouteRouteChildren {
  WorkspaceSlugwithSidebarRouteRoute: typeof WorkspaceSlugwithSidebarRouteRouteWithChildren
  WorkspaceSlugSettingsRouteRoute: typeof WorkspaceSlugSettingsRouteRouteWithChildren
}

const WorkspaceSlugRouteRouteChildren: WorkspaceSlugRouteRouteChildren = {
  WorkspaceSlugwithSidebarRouteRoute:
    WorkspaceSlugwithSidebarRouteRouteWithChildren,
  WorkspaceSlugSettingsRouteRoute: WorkspaceSlugSettingsRouteRouteWithChildren,
}

const WorkspaceSlugRouteRouteWithChildren =
  WorkspaceSlugRouteRoute._addFileChildren(WorkspaceSlugRouteRouteChildren)

interface authRouteRouteChildren {
  authSignInIndexRoute: typeof authSignInIndexRoute
  authSignUpIndexRoute: typeof authSignUpIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInIndexRoute: authSignInIndexRoute,
  authSignUpIndexRoute: authSignUpIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface onboardingRouteRouteChildren {
  onboardingCreateWorkspaceIndexRoute: typeof onboardingCreateWorkspaceIndexRoute
}

const onboardingRouteRouteChildren: onboardingRouteRouteChildren = {
  onboardingCreateWorkspaceIndexRoute: onboardingCreateWorkspaceIndexRoute,
}

const onboardingRouteRouteWithChildren = onboardingRouteRoute._addFileChildren(
  onboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkspaceSlugRouteRoute: WorkspaceSlugRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  onboardingRouteRoute: onboardingRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
