/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthGetSession200ResponseUser
 */
export interface AuthGetSession200ResponseUser {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof AuthGetSession200ResponseUser
     */
    id: string;
    /**
     * a string at most 100 character(s) long
     * @type {string}
     * @memberof AuthGetSession200ResponseUser
     */
    displayName: string;
    /**
     * a non empty string
     * @type {string}
     * @memberof AuthGetSession200ResponseUser
     */
    email: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthGetSession200ResponseUser
     */
    emailVerified: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthGetSession200ResponseUser
     */
    imageUrl: string;
    /**
     * 
     * @type {string}
     * @memberof AuthGetSession200ResponseUser
     */
    activeWorkspaceId: string;
}

/**
 * Check if a given object implements the AuthGetSession200ResponseUser interface.
 */
export function instanceOfAuthGetSession200ResponseUser(value: object): value is AuthGetSession200ResponseUser {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('emailVerified' in value) || value['emailVerified'] === undefined) return false;
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    if (!('activeWorkspaceId' in value) || value['activeWorkspaceId'] === undefined) return false;
    return true;
}

export function AuthGetSession200ResponseUserFromJSON(json: any): AuthGetSession200ResponseUser {
    return AuthGetSession200ResponseUserFromJSONTyped(json, false);
}

export function AuthGetSession200ResponseUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthGetSession200ResponseUser {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'displayName': json['displayName'],
        'email': json['email'],
        'emailVerified': json['emailVerified'],
        'imageUrl': json['imageUrl'],
        'activeWorkspaceId': json['activeWorkspaceId'],
    };
}

export function AuthGetSession200ResponseUserToJSON(json: any): AuthGetSession200ResponseUser {
    return AuthGetSession200ResponseUserToJSONTyped(json, false);
}

export function AuthGetSession200ResponseUserToJSONTyped(value?: AuthGetSession200ResponseUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'displayName': value['displayName'],
        'email': value['email'],
        'emailVerified': value['emailVerified'],
        'imageUrl': value['imageUrl'],
        'activeWorkspaceId': value['activeWorkspaceId'],
    };
}

