/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthSendEmailVerificationOTPRequest
 */
export interface AuthSendEmailVerificationOTPRequest {
    [key: string]: any | any;
    /**
     * a string matching the pattern ^[^@\s]+@[^@\s]+\.[^@\s]{2,}$
     * @type {string}
     * @memberof AuthSendEmailVerificationOTPRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthSendEmailVerificationOTPRequest
     */
    type: AuthSendEmailVerificationOTPRequestTypeEnum;
}


/**
 * @export
 */
export const AuthSendEmailVerificationOTPRequestTypeEnum = {
    SignIn: 'sign-in',
    EmailVerification: 'email-verification',
    ForgetPassword: 'forget-password'
} as const;
export type AuthSendEmailVerificationOTPRequestTypeEnum = typeof AuthSendEmailVerificationOTPRequestTypeEnum[keyof typeof AuthSendEmailVerificationOTPRequestTypeEnum];


/**
 * Check if a given object implements the AuthSendEmailVerificationOTPRequest interface.
 */
export function instanceOfAuthSendEmailVerificationOTPRequest(value: object): value is AuthSendEmailVerificationOTPRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function AuthSendEmailVerificationOTPRequestFromJSON(json: any): AuthSendEmailVerificationOTPRequest {
    return AuthSendEmailVerificationOTPRequestFromJSONTyped(json, false);
}

export function AuthSendEmailVerificationOTPRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSendEmailVerificationOTPRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'email': json['email'],
        'type': json['type'],
    };
}

export function AuthSendEmailVerificationOTPRequestToJSON(json: any): AuthSendEmailVerificationOTPRequest {
    return AuthSendEmailVerificationOTPRequestToJSONTyped(json, false);
}

export function AuthSendEmailVerificationOTPRequestToJSONTyped(value?: AuthSendEmailVerificationOTPRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'email': value['email'],
        'type': value['type'],
    };
}

