/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthSignInWithEmailOTPRequest
 */
export interface AuthSignInWithEmailOTPRequest {
    [key: string]: any | any;
    /**
     * a string matching the pattern ^[^@\s]+@[^@\s]+\.[^@\s]{2,}$
     * @type {string}
     * @memberof AuthSignInWithEmailOTPRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthSignInWithEmailOTPRequest
     */
    otp: string;
}

/**
 * Check if a given object implements the AuthSignInWithEmailOTPRequest interface.
 */
export function instanceOfAuthSignInWithEmailOTPRequest(value: object): value is AuthSignInWithEmailOTPRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('otp' in value) || value['otp'] === undefined) return false;
    return true;
}

export function AuthSignInWithEmailOTPRequestFromJSON(json: any): AuthSignInWithEmailOTPRequest {
    return AuthSignInWithEmailOTPRequestFromJSONTyped(json, false);
}

export function AuthSignInWithEmailOTPRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSignInWithEmailOTPRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'email': json['email'],
        'otp': json['otp'],
    };
}

export function AuthSignInWithEmailOTPRequestToJSON(json: any): AuthSignInWithEmailOTPRequest {
    return AuthSignInWithEmailOTPRequestToJSONTyped(json, false);
}

export function AuthSignInWithEmailOTPRequestToJSONTyped(value?: AuthSignInWithEmailOTPRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'email': value['email'],
        'otp': value['otp'],
    };
}

