/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthGetSession200ResponseUser } from './AuthGetSession200ResponseUser';
import {
    AuthGetSession200ResponseUserFromJSON,
    AuthGetSession200ResponseUserFromJSONTyped,
    AuthGetSession200ResponseUserToJSON,
    AuthGetSession200ResponseUserToJSONTyped,
} from './AuthGetSession200ResponseUser';

/**
 * 
 * @export
 * @interface AuthGetSession200Response
 */
export interface AuthGetSession200Response {
    [key: string]: any | any;
    /**
     * 
     * @type {AuthGetSession200ResponseUser}
     * @memberof AuthGetSession200Response
     */
    user: AuthGetSession200ResponseUser;
}

/**
 * Check if a given object implements the AuthGetSession200Response interface.
 */
export function instanceOfAuthGetSession200Response(value: object): value is AuthGetSession200Response {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function AuthGetSession200ResponseFromJSON(json: any): AuthGetSession200Response {
    return AuthGetSession200ResponseFromJSONTyped(json, false);
}

export function AuthGetSession200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthGetSession200Response {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'user': AuthGetSession200ResponseUserFromJSON(json['user']),
    };
}

export function AuthGetSession200ResponseToJSON(json: any): AuthGetSession200Response {
    return AuthGetSession200ResponseToJSONTyped(json, false);
}

export function AuthGetSession200ResponseToJSONTyped(value?: AuthGetSession200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'user': AuthGetSession200ResponseUserToJSON(value['user']),
    };
}

