/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthSendEmailVerificationOTP200Response
 */
export interface AuthSendEmailVerificationOTP200Response {
}

/**
 * Check if a given object implements the AuthSendEmailVerificationOTP200Response interface.
 */
export function instanceOfAuthSendEmailVerificationOTP200Response(value: object): value is AuthSendEmailVerificationOTP200Response {
    return true;
}

export function AuthSendEmailVerificationOTP200ResponseFromJSON(json: any): AuthSendEmailVerificationOTP200Response {
    return AuthSendEmailVerificationOTP200ResponseFromJSONTyped(json, false);
}

export function AuthSendEmailVerificationOTP200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSendEmailVerificationOTP200Response {
    return json;
}

export function AuthSendEmailVerificationOTP200ResponseToJSON(json: any): AuthSendEmailVerificationOTP200Response {
    return AuthSendEmailVerificationOTP200ResponseToJSONTyped(json, false);
}

export function AuthSendEmailVerificationOTP200ResponseToJSONTyped(value?: AuthSendEmailVerificationOTP200Response | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

