/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PropertyKeyAnyOf } from './PropertyKeyAnyOf';
import {
    PropertyKeyAnyOfFromJSON,
    PropertyKeyAnyOfFromJSONTyped,
    PropertyKeyAnyOfToJSON,
    PropertyKeyAnyOfToJSONTyped,
} from './PropertyKeyAnyOf';

/**
 * 
 * @export
 * @interface PropertyKey
 */
export interface PropertyKey {
    /**
     * 
     * @type {string}
     * @memberof PropertyKey
     */
    tag: PropertyKeyTagEnum;
    /**
     * 
     * @type {string}
     * @memberof PropertyKey
     */
    key: string;
}


/**
 * @export
 */
export const PropertyKeyTagEnum = {
    Symbol: 'symbol'
} as const;
export type PropertyKeyTagEnum = typeof PropertyKeyTagEnum[keyof typeof PropertyKeyTagEnum];


/**
 * Check if a given object implements the PropertyKey interface.
 */
export function instanceOfPropertyKey(value: object): value is PropertyKey {
    if (!('tag' in value) || value['tag'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    return true;
}

export function PropertyKeyFromJSON(json: any): PropertyKey {
    return PropertyKeyFromJSONTyped(json, false);
}

export function PropertyKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyKey {
    if (json == null) {
        return json;
    }
    return {
        
        'tag': json['_tag'],
        'key': json['key'],
    };
}

export function PropertyKeyToJSON(json: any): PropertyKey {
    return PropertyKeyToJSONTyped(json, false);
}

export function PropertyKeyToJSONTyped(value?: PropertyKey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_tag': value['tag'],
        'key': value['key'],
    };
}

