/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkspaceCreateWorkspaceRequest
 */
export interface WorkspaceCreateWorkspaceRequest {
    [key: string]: any | any;
    /**
     * a non empty string
     * @type {string}
     * @memberof WorkspaceCreateWorkspaceRequest
     */
    name: string;
    /**
     * a non empty string
     * @type {string}
     * @memberof WorkspaceCreateWorkspaceRequest
     */
    slug: string;
}

/**
 * Check if a given object implements the WorkspaceCreateWorkspaceRequest interface.
 */
export function instanceOfWorkspaceCreateWorkspaceRequest(value: object): value is WorkspaceCreateWorkspaceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    return true;
}

export function WorkspaceCreateWorkspaceRequestFromJSON(json: any): WorkspaceCreateWorkspaceRequest {
    return WorkspaceCreateWorkspaceRequestFromJSONTyped(json, false);
}

export function WorkspaceCreateWorkspaceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceCreateWorkspaceRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'name': json['name'],
        'slug': json['slug'],
    };
}

export function WorkspaceCreateWorkspaceRequestToJSON(json: any): WorkspaceCreateWorkspaceRequest {
    return WorkspaceCreateWorkspaceRequestToJSONTyped(json, false);
}

export function WorkspaceCreateWorkspaceRequestToJSONTyped(value?: WorkspaceCreateWorkspaceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'name': value['name'],
        'slug': value['slug'],
    };
}

