import {
  CalendarDots,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  Check,
  Circle,
  DotsThree,
  DotsThreeVertical,
  Faders,
  Folder,
  Gear,
  House,
  LinkSimple,
  MagnifyingGlass,
  PencilSimple,
  Plus,
  SidebarSimple,
  SortAscending,
  SortDescending,
  Target,
  TextB,
  TextH,
  TextHOne,
  TextHThree,
  TextHTwo,
  TextItalic,
  TextStrikethrough,
  User,
  UsersFour,
  Wall,
  X,
} from "@phosphor-icons/react";

const Icons = {
  Bold: TextB,
  Calendar: CalendarDots,
  Check: Check,
  ChevronDown: CaretDown,
  ChevronLeft: CaretLeft,
  ChevronRight: CaretRight,
  ChevronUp: CaretUp,
  Circle: Circle,
  DotsThreeHorizontal: DotsThree,
  DotsThreeVertical: DotsThreeVertical,
  Edit: PencilSimple,
  Folder: Folder,
  Headings: TextH,
  HeadingOne: TextHOne,
  HeadingTwo: TextHTwo,
  HeadingThree: TextHThree,
  Home: House,
  Italic: TextItalic,
  Link: LinkSimple,
  Mason: Wall,
  Organization: UsersFour,
  Plus: Plus,
  Search: MagnifyingGlass,
  Settings: Gear,
  Sidebar: SidebarSimple,
  Slider: Faders,
  SortAscending: SortAscending,
  SortDescending: SortDescending,
  StrikeThrough: TextStrikethrough,
  Target: Target,
  User: User,
  X: X,
};

export { Icons };
