import {
  CalendarDots,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  Check,
  Circle,
  DotsThree,
  DotsThreeVertical,
  Faders,
  Folder,
  Gear,
  House,
  LinkSimple,
  MagnifyingGlass,
  PencilSimple,
  Plus,
  SidebarSimple,
  SortAscending,
  SortDescending,
  Target,
  UsersFour,
  Wall,
  X,
} from "@phosphor-icons/react";

const Icons = {
  Calendar: CalendarDots,
  Check: Check,
  ChevronDown: CaretDown,
  ChevronLeft: CaretLeft,
  ChevronRight: CaretRight,
  ChevronUp: CaretUp,
  Circle: Circle,
  DotsThreeHorizontal: DotsThree,
  DotsThreeVertical: DotsThreeVertical,
  Edit: PencilSimple,
  Folder: Folder,
  Home: House,
  Link: LinkSimple,
  Mason: Wall,
  Organization: UsersFour,
  Plus: Plus,
  Search: MagnifyingGlass,
  Settings: Gear,
  Sidebar: SidebarSimple,
  Slider: Faders,
  SortAscending: SortAscending,
  SortDescending: SortDescending,
  Target: Target,
  X: X,
};

export { Icons };
