import {
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  CalendarDotsIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  CheckIcon,
  CircleIcon,
  DotsThreeIcon,
  DotsThreeVerticalIcon,
  EnvelopeIcon,
  FadersIcon,
  FolderIcon,
  GearIcon,
  GithubLogoIcon,
  GoogleLogoIcon,
  HouseIcon,
  LinkSimpleIcon,
  MagnifyingGlassIcon,
  MinusIcon,
  PencilSimpleIcon,
  PlusIcon,
  SidebarSimpleIcon,
  SortAscendingIcon,
  SortDescendingIcon,
  TargetIcon,
  TextBIcon,
  TextHIcon,
  TextHOneIcon,
  TextHThreeIcon,
  TextHTwoIcon,
  TextItalicIcon,
  TextStrikethroughIcon,
  UserIcon,
  UsersFourIcon,
  WallIcon,
  XIcon,
} from '@phosphor-icons/react';

const Icons = {
  ArrowDown: ArrowDownIcon,
  ArrowLeft: ArrowLeftIcon,
  ArrowRight: ArrowRightIcon,
  ArrowUp: ArrowUpIcon,
  Bold: TextBIcon,
  Calendar: CalendarDotsIcon,
  Check: CheckIcon,
  ChevronDown: CaretDownIcon,
  ChevronLeft: CaretLeftIcon,
  ChevronRight: CaretRightIcon,
  ChevronUp: CaretUpIcon,
  Circle: CircleIcon,
  DotsThreeHorizontal: DotsThreeIcon,
  DotsThreeVertical: DotsThreeVerticalIcon,
  Edit: PencilSimpleIcon,
  Mail: EnvelopeIcon,
  Folder: FolderIcon,
  Github: GithubLogoIcon,
  Google: GoogleLogoIcon,
  Headings: TextHIcon,
  HeadingOne: TextHOneIcon,
  HeadingTwo: TextHTwoIcon,
  HeadingThree: TextHThreeIcon,
  Home: HouseIcon,
  Italic: TextItalicIcon,
  Link: LinkSimpleIcon,
  Mason: WallIcon,
  Minus: MinusIcon,
  Organization: UsersFourIcon,
  Plus: PlusIcon,
  Search: MagnifyingGlassIcon,
  Settings: GearIcon,
  Sidebar: SidebarSimpleIcon,
  Slider: FadersIcon,
  SortAscending: SortAscendingIcon,
  SortDescending: SortDescendingIcon,
  StrikeThrough: TextStrikethroughIcon,
  Target: TargetIcon,
  User: UserIcon,
  X: XIcon,
};

export { Icons };
