/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HttpApiDecodeError,
} from '../models/index';
import {
    HttpApiDecodeErrorFromJSON,
    HttpApiDecodeErrorToJSON,
} from '../models/index';

/**
 * 
 */
export class PingApi extends runtime.BaseAPI {

    /**
     */
    async pingPingRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/ping`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async pingPing(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.pingPingRaw(initOverrides);
    }

}
