/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthSendEmailVerificationOTP200Response,
  HttpApiDecodeError,
  WorkspaceCreateWorkspaceRequest,
} from '../models/index';
import {
    AuthSendEmailVerificationOTP200ResponseFromJSON,
    AuthSendEmailVerificationOTP200ResponseToJSON,
    HttpApiDecodeErrorFromJSON,
    HttpApiDecodeErrorToJSON,
    WorkspaceCreateWorkspaceRequestFromJSON,
    WorkspaceCreateWorkspaceRequestToJSON,
} from '../models/index';

export interface WorkspaceCreateWorkspaceOperationRequest {
    workspaceCreateWorkspaceRequest: WorkspaceCreateWorkspaceRequest;
}

/**
 * 
 */
export class WorkspaceApi extends runtime.BaseAPI {

    /**
     */
    async workspaceCreateWorkspaceRaw(requestParameters: WorkspaceCreateWorkspaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthSendEmailVerificationOTP200Response>> {
        if (requestParameters['workspaceCreateWorkspaceRequest'] == null) {
            throw new runtime.RequiredError(
                'workspaceCreateWorkspaceRequest',
                'Required parameter "workspaceCreateWorkspaceRequest" was null or undefined when calling workspaceCreateWorkspace().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/workspace/workspace`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WorkspaceCreateWorkspaceRequestToJSON(requestParameters['workspaceCreateWorkspaceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthSendEmailVerificationOTP200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async workspaceCreateWorkspace(workspaceCreateWorkspaceRequest: WorkspaceCreateWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthSendEmailVerificationOTP200Response> {
        const response = await this.workspaceCreateWorkspaceRaw({ workspaceCreateWorkspaceRequest: workspaceCreateWorkspaceRequest }, initOverrides);
        return await response.value();
    }

}
